### ISSUE TITLE
Set up a basic (minimal) CI test

### ISSUE THREAD

**Issue by Spindel** [cts-admin/cts#3]
For GitHub, [Travis CI](https://docs.travis-ci.com/user/getting-started/) is the recommended

Set up a basic CI pipeline that:  
- [ ]  installs the application with `pip install .`   

This is the "Hello World" verion of a CI system, but requires you to read up a bit on getting the basics running.  

A minimal Travis setup looks like:

```
  language: python
  python:
    - 3.6
    - nightly
  script:
    - pip install -r requirements.txt
    - pip install cts
```
